name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Create and activate the venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Check the installations
        run: |
          simple_lama --help
          flask --version

